export enum RouteEnum {
  HOME = '/',
  LOGIN = '/auth/login',
  REGISTER = '/auth/register',
  CREATE_PASSWORD = '/auth/create-password',
  FORGOT_PASSWORD = '/auth/forgot-password',
  AUTHENTICATED = '/authenticated',
  ATHLETES = '/authenticated/athletes',
  CREATE_ATHLETE = '/authenticated/athletes/create',
  UPDATE_ATHLETE = '/authenticated/athletes/:ID/update',
  MONITORY = '/authenticated/athletes/:ID/monitoring',
  TRAININGS = '/authenticated/athletes/:ID/training',
  CREATE_TRAINING = '/authenticated/athletes/:ID/training/create',
  UPDATE_TRAINING = '/authenticated/athletes/:ID/training/:CHILD_ID/update',
  TRAINING_PLANNING = '/authenticated/athletes/:ID/training-planning',
  CREATE_TRAINING_PLANNING = '/authenticated/athletes/:ID/training-planning/create',
  UPDATE_TRAINING_PLANNING = '/authenticated/athletes/:ID/training-planning/:CHILD_ID/update',
  TRAINING_TYPES = '/authenticated/training-types',
  TERMS_OF_USE = '/terms-of-use',
  PRIVACY_POLICY = '/privacy-policy',
}
